name: teller-ms - Snapshot Docker Image

on:
  push:
  pull_request:
  repository_dispatch:
    types: [build]

jobs:
  build-and-push:
    name: Build image and push to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-grdl
      - name: Build with Gradle
        run: ./gradlew publishToMavenLocal
      - name: Upload jar
        uses: actions/upload-artifact@v1
        with:
          name: teller-ms - Boot Jar
          path: ./service/build/libs/service-0.1.0.BUILD-SNAPSHOT-boot.jar
      - name: Build Docker image and push
        uses: docker/build-push-action@v1
        with:
          path: ./instate-fineract-corda-bridge/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: 'instateteam/fineract-cn-teller/teller-ms'
          tag_with_ref: true